---
title: "My interactive Rmd!"
author: "Grace Brofman"
date: "1/26/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(palmerpenguins)
```

```{r flippers, echo = FALSE}

inputPanel(
  
  selectInput(inputId = "pick_spp",  # internal name
              label = "Pick your penguin species:", # user-facing name
              choices = c("Adèlie" = "Adelie", "Cool chistrap" = "Chinstrap", "Gentoo"), selected = "Gentoo"), # can specify what you want the choices to look like, then let R know what that choice refers to in the dataset (e.g. Adelie with or without accent over e)
  # `selected` refers to which option will automatically be selected when app is opened
  
  sliderInput(inputId = "pt_size",
              label = "Set you point size:",
              min = 1,
              max = 10,
              step = 0.5,
              value = 5) # specifies starting value
  
)

# reactive subset: start with df penguins, and then filter it to select the species to match what was identified under pick_spp (inputId)
penguin_set <- reactive({
  penguins %>% 
    filter(species == input$pick_spp)
})


# render my plot (with a reactive plot)
renderPlot({
  
  ggplot(data = penguin_set(), aes(x = flipper_length_mm, y = body_mass_g)) + # !! have to include () at the end of a reactive df!!
    geom_point(size = input$pt_size)
  
})


```


